### ISSUE TITLE
why 'table' before the full url path '/table/__api/11/promotion/getPromotionList'...

### ISSUE THREAD

**Issue by jayzhou215** [Tianlikai/mobxSpa#12]
In _mocker_/index.js, proxy like '/__api/8/user/login' is easy to understand, since the baseUrl is '__api' and url is '/8/user/login'.
But I feel puzzled about 'table' as the prefix of '/table/__api/11/promotion/getPromotionList'.

**Comment by Tianlikai** [comment]
> In _mocker_/index.js, proxy like '/__api/8/user/login' is easy to understand, since the baseUrl is '__api' and url is '/8/user/login'.
> But I feel puzzled about 'table' as the prefix of '/table/__api/11/promotion/getPromotionList'.

API request initiated under route '/table'

**Comment by jayzhou215** [comment]
thanks
